/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PregledRouteImport } from './routes/pregled'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoSlugRouteImport } from './routes/demo.$slug'
import { Route as DemoSlugIndexRouteImport } from './routes/demo.$slug.index'
import { Route as DemoSlugPregledRouteImport } from './routes/demo.$slug.pregled'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PregledRoute = PregledRouteImport.update({
  id: '/pregled',
  path: '/pregled',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugRoute = DemoSlugRouteImport.update({
  id: '/demo/$slug',
  path: '/demo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugIndexRoute = DemoSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoSlugRoute,
} as any)
const DemoSlugPregledRoute = DemoSlugPregledRouteImport.update({
  id: '/pregled',
  path: '/pregled',
  getParentRoute: () => DemoSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pregled': typeof PregledRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/$slug': typeof DemoSlugRouteWithChildren
  '/demo/$slug/pregled': typeof DemoSlugPregledRoute
  '/demo/$slug/': typeof DemoSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pregled': typeof PregledRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/$slug/pregled': typeof DemoSlugPregledRoute
  '/demo/$slug': typeof DemoSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pregled': typeof PregledRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/$slug': typeof DemoSlugRouteWithChildren
  '/demo/$slug/pregled': typeof DemoSlugPregledRoute
  '/demo/$slug/': typeof DemoSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pregled'
    | '/sitemap.xml'
    | '/demo/$slug'
    | '/demo/$slug/pregled'
    | '/demo/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pregled' | '/sitemap.xml' | '/demo/$slug/pregled' | '/demo/$slug'
  id:
    | '__root__'
    | '/'
    | '/pregled'
    | '/sitemap.xml'
    | '/demo/$slug'
    | '/demo/$slug/pregled'
    | '/demo/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PregledRoute: typeof PregledRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoSlugRoute: typeof DemoSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregled': {
      id: '/pregled'
      path: '/pregled'
      fullPath: '/pregled'
      preLoaderRoute: typeof PregledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug': {
      id: '/demo/$slug'
      path: '/demo/$slug'
      fullPath: '/demo/$slug'
      preLoaderRoute: typeof DemoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug/': {
      id: '/demo/$slug/'
      path: '/'
      fullPath: '/demo/$slug/'
      preLoaderRoute: typeof DemoSlugIndexRouteImport
      parentRoute: typeof DemoSlugRoute
    }
    '/demo/$slug/pregled': {
      id: '/demo/$slug/pregled'
      path: '/pregled'
      fullPath: '/demo/$slug/pregled'
      preLoaderRoute: typeof DemoSlugPregledRouteImport
      parentRoute: typeof DemoSlugRoute
    }
  }
}

interface DemoSlugRouteChildren {
  DemoSlugPregledRoute: typeof DemoSlugPregledRoute
  DemoSlugIndexRoute: typeof DemoSlugIndexRoute
}

const DemoSlugRouteChildren: DemoSlugRouteChildren = {
  DemoSlugPregledRoute: DemoSlugPregledRoute,
  DemoSlugIndexRoute: DemoSlugIndexRoute,
}

const DemoSlugRouteWithChildren = DemoSlugRoute._addFileChildren(
  DemoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PregledRoute: PregledRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoSlugRoute: DemoSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
